version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./.docker/postgres:/data/db
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      redis-server
    networks:
      - app-network

  # Monitoring & Observability
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - ./.docker/redisinsight:/db
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    volumes:
      - ./.docker/pgadmin:/root/.pgadmin
    ports:
      - 5433:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
