version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./.docker/postgres:/data/db
    ports:
      - 5432:5432
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      redis-server
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
