version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./.docker/postgres:/data/db
    ports:
      - 5432:5432
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    volumes:
      - ./.docker/pgadmin:/root/.pgadmin
    ports:
      - 5433:80
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      redis-server
    networks:
      - app-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_PORT=6379
    ports:
      - 8081:8081
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
