version: '3'
services:
  devtalk-postgres:
    image: postgres
    volumes:
      - ./db:/data/db
    ports:
      - 5432:5432
    networks:
      - app-network

  devtalk-redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      redis-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
