export enum StatusCodeEnum {
	BAD_REQUEST = 400,
	NOT_FOUND = 404,
	TOO_MANY_REQUESTS = 429,
	INTERNAL_SERVER_ERROR = 500
}

export enum CachingCategoriesEnum {
	HOURLY_UPDATES = 'HOURLY_UPDATES',
	DAILY_TESTS_AMOUNT = 'DAILY_TESTS_AMOUNT',
	DAILY_IRD = 'DAILY_IRD'
}
