export enum StatusCodeEnum {
	BAD_REQUEST = 400,
	NOT_FOUND = 404,
	TOO_MANY_REQUESTS = 429,
	INTERNAL_SERVER_ERROR = 500
}

export enum CachingCategoriesEnum {
	COUNTRIES_DATA = 'COUNTRIES_DATA',
	TESTS_AMOUNT = 'TESTS_AMOUNT',
	DAILY_STATS = 'DAILY_STATS'
}
